# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_within_wrappers", use_symbols = TRUE, package_name = "within")

#' @usage NULL
#' @useDynLib within, .registration = TRUE
NULL

#' Solve fixed-effects demeaning for a single response vector.
#'
#' @param categories Integer matrix (n_obs x n_factors) of factor levels (0-based).
#' @param y Numeric vector of length n_obs.
#' @param method Solver method: "cg" (default) or "gmres".
#' @param tol Convergence tolerance (default 1e-8).
#' @param maxiter Maximum iterations (default 1000).
#' @param restart GMRES restart parameter (default 30, ignored for CG).
#' @param preconditioner Preconditioner: "additive" (default), "multiplicative", or "off".
#' @param weights Optional observation weights (length n_obs).
#' @return A named list with components x, demeaned, converged, iterations,
#'         residual, time_total, time_setup, time_solve.
solve <- function(categories, y, method, tol, maxiter, restart, preconditioner, weights) .Call(wrap__solve, categories, y, method, tol, maxiter, restart, preconditioner, weights)

#' Solve fixed-effects demeaning for multiple response vectors (batch).
#'
#' @param categories Integer matrix (n_obs x n_factors) of factor levels (0-based).
#' @param Y Numeric matrix (n_obs x k) where each column is a response vector.
#' @param method Solver method: "cg" (default) or "gmres".
#' @param tol Convergence tolerance (default 1e-8).
#' @param maxiter Maximum iterations (default 1000).
#' @param restart GMRES restart parameter (default 30, ignored for CG).
#' @param preconditioner Preconditioner: "additive" (default), "multiplicative", or "off".
#' @param weights Optional observation weights (length n_obs).
#' @return A named list with components x, demeaned (matrices), converged,
#'         iterations, residual, time_solve (vectors), and time_total (scalar).
solve_batch <- function(categories, y, method, tol, maxiter, restart, preconditioner, weights) .Call(wrap__solve_batch, categories, y, method, tol, maxiter, restart, preconditioner, weights)


# nolint end
