[package]
name = "within-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
name = "_within"
crate-type = ["cdylib"]

[dependencies]
within = { path = "../within" }
schwarz-precond.workspace = true
postcard.workspace = true
pyo3 = { version = "0.25", features = ["extension-module"] }
numpy = "0.25"
