[package]
name = "within-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
name = "_within"
crate-type = ["cdylib"]

[dependencies]
within = { path = "../within", features = ["ndarray"] }
postcard.workspace = true
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py39"] }
numpy = "0.29"

[lints]
workspace = true
