# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_withinr_wrappers", use_symbols = TRUE, package_name = "withinr")

#' @usage NULL
#' @useDynLib withinr, .registration = TRUE
NULL

solve_impl <- function(categories, y, options, weights, preconditioner) .Call(wrap__solve_impl, categories, y, options, weights, preconditioner)

solve_batch_impl <- function(categories, y_matrix, options, weights, preconditioner) .Call(wrap__solve_batch_impl, categories, y_matrix, options, weights, preconditioner)

solver_new_impl <- function(categories, weights, preconditioner) .Call(wrap__solver_new_impl, categories, weights, preconditioner)

solver_solve_impl <- function(solver, y, options) .Call(wrap__solver_solve_impl, solver, y, options)

solver_solve_batch_impl <- function(solver, y_matrix, options) .Call(wrap__solver_solve_batch_impl, solver, y_matrix, options)

solver_preconditioner_impl <- function(solver) .Call(wrap__solver_preconditioner_impl, solver)

solver_n_dofs_impl <- function(solver) .Call(wrap__solver_n_dofs_impl, solver)

solver_n_obs_impl <- function(solver) .Call(wrap__solver_n_obs_impl, solver)

preconditioner_apply_impl <- function(preconditioner, x) .Call(wrap__preconditioner_apply_impl, preconditioner, x)

preconditioner_nrows_impl <- function(preconditioner) .Call(wrap__preconditioner_nrows_impl, preconditioner)

preconditioner_ncols_impl <- function(preconditioner) .Call(wrap__preconditioner_ncols_impl, preconditioner)

preconditioner_variant_impl <- function(preconditioner) .Call(wrap__preconditioner_variant_impl, preconditioner)

preconditioner_serialize_impl <- function(preconditioner) .Call(wrap__preconditioner_serialize_impl, preconditioner)

preconditioner_deserialize_impl <- function(data) .Call(wrap__preconditioner_deserialize_impl, data)


