# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_withinr_wrappers", use_symbols = TRUE, package_name = "withinr")

#' @usage NULL
#' @useDynLib withinr, .registration = TRUE
NULL

#' @rdname solve_impl
#' @keywords internal
solve_impl <- function(categories, y, weights, method, tol, maxiter, restart, preconditioner) {
  .Call("wrap__solve_impl", categories, y, weights, method, tol, maxiter, restart, preconditioner)
}

#' @rdname solve_batch_impl
#' @keywords internal
solve_batch_impl <- function(categories, y_matrix, weights, method, tol, maxiter, restart, preconditioner) {
  .Call("wrap__solve_batch_impl", categories, y_matrix, weights, method, tol, maxiter, restart, preconditioner)
}
